# -*- coding: utf-8 -*-
"""BP_author's_solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rGjiOikrxCo4cntefNtFqtimUnF0HCsE

# Let Me Hear The Music

# Contents <a id='back'></a>

* [Introduction](#intro)
* [Stage 1. Data overview](#data_review)
    * [Conclusions](#data_review_conclusions)
* [Stage 2. Data preprocessing](#data_preprocessing)
    * [2.1 Header style](#header_style)
    * [2.2 Missing values](#missing_values)
    * [2.3 Duplicates](#duplicates)
    * [2.4 Conclusions](#data_preprocessing_conclusions)
* [Stage 3. Testing the hypothesis](#hypothesis)
    * [3.1 Hypothesis 1: user activity in the two cities](#activity)
* [Findings](#end)

## Introduction <a id='intro'></a>
As a data analyst, your work involves analyzing data to extract valuable insights and make data-driven decisions. This involves different stages, such as data overview, preprocessing, and testing hypotheses.

Whenever we're doing research, we need to formulate hypotheses that we can then test. Sometimes we accept these hypotheses; other times, we reject them. To make the right decisions, a business must be able to understand whether or not it's making the right assumptions.

In this project, you'll compare the music preferences of the cities of Springfield and Shelbyville. You'll study real online music stream data to test the hypothesis below and compare user behavior for these two cities.

### Goal:
Test the hypothesis:
1. User activity differs depending on the day of the week and from city to city.


### Stages
Data on user behavior is stored in the file `/datasets/music_project_en.csv`. There is no information about the quality of the data, so you will need to explore it before testing the hypothesis.

First, you'll evaluate the quality of the data and see whether its issues are significant. Then, during data preprocessing, you will try to account for the most critical problems.

Your project will consist of three stages:
 1. Data overview
 2. Data preprocessing
 3. Testing the hypothesis

[Back to Contents](#back)

## Stage 1. Data overview <a id='data_review'></a>

Open the data and explore it.
"""

"""You'll need `pandas`, so import it."""

# importing pandas
import pandas as pd
pd.set_option('display.max_columns', None)

"""Read the file `music_project_en.csv` from the `/datasets/` folder and save it in the `df` variable:"""

# reading the file and storing it to df
df = pd.read_csv("datasets/music_project_en.csv")

"""Print the first 10 table rows:"""

# obtaining the first 10 rows from the df table
df.head(10)

"""Obtain the general information about the table with one command. You know the method that outputs the general information we need."""

# obtaining the general information about our data
df.info()

"""These are our observations about the table. It contains seven columns. They all store the same data type: `object`.

According to the documentation:
- `' userID'` — user identifier
- `'Track'` — track title
- `'artist'` — artist's name
- `'genre'` — track genre
- `'City'` — user's city
- `'time'` — the exact time the track was played
- `'Day'` — day of the week

We can see three issues with style in the table headers:
1. Some headers are uppercase, some are lowercase.
2. There are spaces in some headers.
3. `Detect the third issue yourself and describe it here`.

3. The number of values in each column is different. This means the data contains missing values.

### Your Observations <a id='data_review_conclusions'></a>
What kind of data do we have on hands in the rows? And how can we understand the columns?

Answer: Each row in the table stores data on a track that was played. Some columns describe the track itself: its title, artist and genre. The rest convey information about the user: the city they come from, the time they played the track.

Is the data enough to answer to our hypothesis or do we need more data?

Answer: As our hypothesis depends on data for the city, day of the week it's clear that the data is sufficient to test the hypothesis, as we have access to all these data.

Did you notice any problems in the data like missing values, duplicates or wrong data types?

Yes, there is a NaN in the table and the data types are wrong for some column.

And there is our problem with missing values as well.

To move forward, we need to preprocess the data.

[Back to Contents](#back)

## Stage 2. Data preprocessing <a id='data_preprocessing'></a>

The goal here is to prepare the data to be analyzed.
The first step is to resolve any problems with the header. Then we can advance to missing and duplicated values. Let's start.

Correct the formatting in the table headers.

### Header style <a id='header_style'></a>
Print the table headers (the column names):
"""

# print the column names
df.columns

"""Change table headers according to the rules of good style:
* All characters must be lowercase
* Delete spaces
* If the name has several words, use snake_case

Previously, you have learned about the automated way of renaming the column. Let's apply it now. Use the for loop to iterate over the column names and make all characters lowercase. When you are done print the table header again:
"""

# Looping into the headers and making all lowercase

new_names = []

for old_name in df.columns:
  lowercase_name = old_name.lower()
  new_names.append(lowercase_name)

df.columns = new_names
df.columns

"""Now, following the same approach, delete the spaces at the beginning and at the end of the column names and print the column names again:"""

# Looping into the headers and removing spaces

new_names = []

for old_name in df.columns:
  lowercase_name = old_name.strip()
  new_names.append(lowercase_name)

df.columns = new_names
df.columns

"""We need to apply the snake-case rule to the `userid` column. It should be `user_id`. Rename the name of this column and print the name for all column when you are done."""

# Renaming the "userid" column

df.rename(columns={'userid':'user_id'}, inplace=True)
df.columns

"""Check the result. Print the headers once again:"""

# checking result: the list of headers
df.columns

"""[Back to Contents](#back)

### Missing values <a id='missing_values'></a>
 First, find the number of missing values in the table. You need two use two methods in a sequence to obtain the number of missing values.
"""

# calculating the number of missing values
df.isna().sum()

"""Not all missing values affect the research. For instance, the missing values in `track` and `artist` are not critical. You can simply replace them with default values such as the string `'unknown'`.

But missing values in `'genre'` can affect the comparison of music preferences in Springfield and Shelbyville. In real life, it would be useful to learn the reasons why the data is missing and try to make up for them. But we do not have that opportunity in this project. So you will have to:
* Fill in these missing values with a default value
* Evaluate how much the missing values may affect your analysis

Replace the missing values in the `'track'`, `'artist'`, and `'genre'` columns with the string `'unknown'`. As we have shown previously in the lessons, the best way of doing it is to create a list that will store the names of the columns where the replacement is needed. Then, use this list and iterate over the columns where the replacement is needed and do the actual replacement.
"""

# looping over headers and replacing missing values with 'unknown'
columns_to_replace = ['track','artist','genre']
for col in columns_to_replace:
    df[col].fillna('unknown', inplace=True)

"""Check the result now to make sure that after the replacement there are no missing values in the dataset. To do this, count the missing values again."""

# counting missing values
df.isna().sum()

"""[Back to Contents](#back)

### Duplicates <a id='duplicates'></a>
Find the number of explicit duplicates in the table. Again, you need to apply two methods in a sequence to get the number of explicit duplicates.
"""

# counting explicit duplicates
df.duplicated().sum()

"""Now, drop all of the duplicates. To do this, call the method that does exactly this."""

# removing explicit duplicates
df.drop_duplicates(inplace=True)

"""Let's now check whether we successfully dropped all of the duplicates. Count explicit duplicates once more time to make sure you have removed all of them:"""

# checking for duplicates again
df.duplicated().sum()

"""Now we want to get rid of implicit duplicates in the `genre` column. For example, the name of a genre can be written in different ways. Such errors will also affect the result. View all of the unique genre names now and pay carefull attention to options for the hiphop genre. There are four different names for this genre that exist. What are these names? Fint them out by examining the unique genre names."""

# viewing unique genre names
df.genre.unique()

"""To do this, let's first print a list of unique genre names, sorted in alphabetical order. To do so:
* Extract the `genre` column from the DataFrame
* Call the method that will return all unique values in the extracted column
* Finally, call the function for sorting to sort the result

Look through the list to find implicit duplicates of the genre `hiphop`. These could be names written incorrectly or alternative names of the same genre.

You will see the following implicit duplicates:
* `hip`
* `hop`
* `hip-hop`

To get rid of them, create a function called `replace_wrong_genres()` with two parameters:
* `wrong_genres=` — this is a list that contains all of the values that you need to replace
* `correct_genre=` — this is a string that you are going to use for replacement

As a result, the function should correct the names in the `'genre'` column from the `df` table, i.e. replace each value from the `wrong_genres` list with the value in `correct_genre`.

Within the body of the function, use a `'for'` loop to iterate over the list of wrong genres, extract the `'genre'` column and apply the `replace` method to make corrections.
"""

# function for replacing implicit duplicates
def replace_wrong_genres(wrong_genres, correct_genre):
    for g in wrong_genres:
        df['genre'].replace(g,correct_genre, inplace=True)

"""Now, call `replace_wrong_genres()` and pass such arguments so that it clears implicit duplcates (`hip`, `hop`, and `hip-hop`) and replaces them with `hiphop`:"""

# removing implicit duplicates
replace_wrong_genres(['hip','hop','hip-hop'],'hiphop')

"""Now, let's check the result. Make sure the duplicate names were removed. Print the list of unique values from the `'genre'` column one more time:"""

# checking for implicit duplicates
sorted(df.genre.unique())

"""[Back to Contents](#back)

### Your Observations <a id='data_preprocessing_conclusions'></a>
We detected three issues with the data:

- Incorrect header styles
- Missing values
- Explicit and implicit duplicates

To make it easier to process the table, we have cleaned up the headers. This means that the table headers are now more descriptive and easier to understand.

Additionally, we have also replaced all missing values with the string `'unknown'`. This was done to ensure that we have complete data to work with and that we can perform a thorough analysis.

Another step we have taken to improve the accuracy of our analysis is the removal of duplicates. By removing duplicates, we can ensure that our analysis is based on unique data points and that our conclusions are more reliable.

Now we can move on to testing the hypothesis.

[Back to Contents](#back)

## Stage 3. Testing the hypothesis <a id='hypothesis'></a>

### Hypothesis: comparing user behavior in two cities <a id='activity'></a>

The hypothesis states that there are differences in the way that music is consumed by users in Springfield and Shelbyville. To test this, use the data from three days of the week: Monday, Wednesday, and Friday.

* Group the users by city.
* Compare the number of tracks each group played on Monday, Wednesday, and Friday.

Perform each computation separately.

The first step is to evaluate user activity in each city. Remember about the split-apply-combine stages we talked about previously in the lesson. Your goal now is to group the data by city, apply the appropriate method for counting during the apply stage, and then find the number of songs played in each group by specifying the column to get the count for.

Here is an example of how the final result should look like:
`df.groupby(by='....')['column'].method()`
"""

# Counting up the tracks played in each city
df.groupby(by='city')['track'].count()

"""As a result, we see that Springfield has more tracks played than Shelbyville. However, this does not necessarily mean that citizens of Springfield listen to music more frequently. The possible larger size of a city simply results in a greater number of users.

Now let's group the data by day of the week and find the number of tracks played on Monday, Wednesday, and Friday. Use the same approach as before but now we need different grouping.

"""

# Calculating tracks played on each day of the week
df.groupby(by=['day'])['track'].count()

"""As a result we see that Wednesday is the quietest day overall. However, if we consider the two cities separately, we might reach a different conclusion.

You have learned how to count entries by grouping them by city or day. Now, you need to write a function that can count entries based on both criteria simultaneously.

Create the `number_tracks()` function to calculate the number of songs played for a given day **and** city. The function should accept two parameters:

- `day`: a day of the week to filter by. For instance, `'Monday'`.
- `city`: a city to filter by. For instance, `'Springfield'`.

Within the function, you will apply consecutive filtering with logical indexing.

First, filter the data by day and then filter the resulting table by city.

After filtering the data by two criteria, count the number of 'user_id' column values in the resulting table. This count represents the number of entries you are looking for. Store the result in a new variable and return it from the function.
"""

# <creating the function number_tracks()>
# Declare the function number_tracks() with two parameters: day= and city=.
def number_tracks(day, city):
    # Store the DataFrame rows where the value in the 'day' column is equal to the day= parameter
    track_list = df[df['day'] == day]

    # Filter the rows where the value in the 'city' column is equal to the city= parameter
    track_list = track_list[track_list['city'] == city]

    # Extract the 'user_id' column from the filtered table and apply the count() method
    track_list_count = track_list['user_id'].count()

    # Return the number of 'user_id' column values
    return track_list_count

"""Call `number_tracks()` six times, changing the parameter values, so that you retrieve the data on both cities for each of the three days."""

# the number of songs played in Springfield on Monday
print(number_tracks('Monday', 'Springfield'))

# the number of songs played in Shelbyville on Monday
print(number_tracks('Monday', 'Shelbyville'))

# the number of songs played in Springfield on Wednesday
print(number_tracks('Wednesday', 'Springfield'))

# the number of songs played in Shelbyville on Wednesday
print(number_tracks('Wednesday', 'Shelbyville'))

# the number of songs played in Springfield on Friday
print(number_tracks('Friday', 'Springfield'))

# the number of songs played in Shelbyville on Friday
print(number_tracks('Friday', 'Shelbyville'))

"""Make your conclusions about the hypothesis that you test.

**Conclusions**

The data reveals differences in user behavior:

- In Springfield, the number of songs played peaks on Mondays and Fridays, while on Wednesday there is a decrease in activity.
- In Shelbyville, on the contrary, users listen to music more on Wednesday. User activity on Monday and Friday is smaller.

So the hypothesis seems to be correct. We accept it.

[Back to Contents](#back)

# Findings <a id='end'></a>

We tested the following hypothesis that the sser activity varies depending on the day of the week and the city.

After analyzing the data, we reached the conclusion that the sser activity in Springfield and Shelbyville is affected by the day of the week, but the cities differ in their patterns.

The hypothesis can be fully accepted.


### Note
In real research projects, statistical hypothesis testing is more precise and quantitative. Also note that conclusions about an entire city cannot always be drawn from data from just one source.

You will learn more about hypothesis testing in the statistical data analysis sprint.

[Back to Contents](#back)
"""